import { lazy } from 'react'

export const HomePage = lazy(() => import('@/pages/Home/HomePage'))
export const BuyPage = lazy(() => import('@/pages/Buy/BuyPage'))
export const BuyNewPage = lazy(() => import('@/pages/Buy/BuyNewPage'))
export const ProducePage = lazy(() => import('@/pages/Produce/ProducePage'))
export const ProduceNewPage = lazy(() => import('@/pages/Produce/ProduceNewPage'))
export const BottlePage = lazy(() => import('@/pages/Bottle/BottlePage'))
export const BottleNewPage = lazy(() => import('@/pages/Bottle/BottleNewPage'))
export const SellPage = lazy(() => import('@/pages/Sell/SellPage'))
export const SellNewPage = lazy(() => import('@/pages/Sell/SellNewPage'))
export const ExpensePage = lazy(() => import('@/pages/Expense/ExpensePage'))
export const ExpenseNewPage = lazy(() => import('@/pages/Expense/ExpenseNewPage'))
export const StockPage = lazy(() => import('@/pages/Stock/StockPage'))
export const BillsPage = lazy(() => import('@/pages/Bills/BillsPage'))
export const BillDetailPage = lazy(() => import('@/pages/Bills/BillDetailPage'))
export const CustomersPage = lazy(() => import('@/pages/Customers/CustomersPage'))
export const ReportsPage = lazy(() => import('@/pages/Reports/ReportsPage'))
export const SettingsPage = lazy(() => import('@/pages/Settings/SettingsPage'))
export const MorePage = lazy(() => import('@/pages/More/MorePage'))
